version: '3.8'

services:
  cocos-db:
    image: postgres:13
    environment:
      POSTGRES_DB: cocos
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: myS3crEtPass01
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - cocos_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cocos_db:
